import AppKit
import Foundation

enum Clipboard {
    /// Marker recognised by clipboard managers (and respected by several sync
    /// tools) meaning "do not record or sync this item". We are writing to the
    /// pasteboard very frequently; without this, history fills with noise and
    /// every selection would be eligible for Universal Clipboard sync.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    static var currentString: String? {
        NSPasteboard.general.string(forType: .string)
    }

    /// Increments on every write by any process. Used to detect that something
    /// else copied while a gesture was being resolved.
    static var changeCount: Int {
        NSPasteboard.general.changeCount
    }

    /// Writes plain text. Returns false when the write was skipped.
    ///
    /// `force` rewrites even when the string already matches. That is needed
    /// after an app's own copy: the text is identical, but the pasteboard also
    /// carries the app's RTF/HTML flavors, and rewriting is what strips them.
    @discardableResult
    static func write(_ text: String, concealed: Bool, force: Bool = false) -> Bool {
        // Never clobber a good clipboard with nothing.
        guard !text.isEmpty, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return false
        }
        // Skip no-op writes so clipboard-manager history stays clean.
        guard force || text != currentString else { return false }

        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        if concealed {
            pasteboard.setData(Data(), forType: concealedType)
        }
        return pasteboard.setString(text, forType: .string)
    }

    /// A full copy of the pasteboard, across all flavors, so the Cmd+C fallback
    /// can put things back if the copy did not produce usable text.
    ///
    /// Restoring is inherently lossy: promised file data and some custom flavors
    /// cannot be reproduced. That is one more reason the fallback path is gated
    /// as narrowly as possible.
    static func snapshot() -> (changeCount: Int, items: [NSPasteboardItem]) {
        let pasteboard = NSPasteboard.general
        let copies: [NSPasteboardItem] = (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    copy.setData(data, forType: type)
                }
            }
            return copy
        }
        return (pasteboard.changeCount, copies)
    }

    /// Flavors we deliberately do NOT restore.
    ///
    /// Rewriting an item gives it a fresh change count, which orphans a password
    /// manager's pending auto-clear — the password would then sit on the
    /// clipboard indefinitely. Leaving it destroyed is the safer failure, so
    /// this trades a lost clipboard for not resurrecting a secret that can no
    /// longer be auto-cleared.
    ///
    /// `AutoGeneratedType` is deliberately absent: it marks tool-generated
    /// content, not secrets, and skipping its restore would lose data for no
    /// safety gain.
    private static let doNotRestoreTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.agilebits.onepassword",
        "com.bitwarden.pasteboard",
    ]

    static func restore(_ snapshot: (changeCount: Int, items: [NSPasteboardItem])) {
        guard !snapshot.items.isEmpty else { return }

        let carriesSensitiveFlavor = snapshot.items.contains { item in
            item.types.contains { doNotRestoreTypes.contains($0.rawValue) }
        }
        guard !carriesSensitiveFlavor else { return }

        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.writeObjects(snapshot.items)
    }
}
